-- 分类表
CREATE TABLE navigation_category (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    title VARCHAR(255),
    sort INTEGER,
    del_flag INTEGER,
    create_by VARCHAR(255),
    create_time TIMESTAMP
);

-- 导航表
CREATE TABLE web_navigation (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    title VARCHAR(255),
    content TEXT,
    detail TEXT,
    url VARCHAR(255),
    image_url VARCHAR(255),
    thumbnail_url VARCHAR(255),
    collection_time TIMESTAMP,
    tag_name VARCHAR(255),
    website_data JSONB,
    star_rating INTEGER,
    category_name VARCHAR(255)
);

-- 查询submit表，按提交时间，status=0（未处理），按照is_feature desc, created_at asc
-- 得到结果后，写入web_navigation，同时修改submit的status=1

CREATE TABLE IF NOT EXISTS public.submit (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NULL,
  url text NULL,
  email text NULL,
  is_feature integer default 0,
  status integer default 0,
  CONSTRAINT submit_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

